name: Task 1

on: [push]

jobs:
  RunScripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Running  # Add a space before 'name'
      run: python *.py
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: saved-files
        path: output1.png

    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        if [-z "$(git status --porcelain)"]; then
          echo "::set-output name=push::false"
        else
          git commit -m "Add changes" -a
          echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
    if: steps.commit.outputs.push == 'true'
    uses: ad-m/github-push-action@master
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}